# Generated by Django 4.1.7 on 2023-04-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_remove_watchlist_platfrom_watchlist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
